### ISSUE TITLE
signing 2/2 from mobile with paytaca for mistswap swap fails on paytaca app

### ISSUE THREAD

**Issue by kasumi-1** [mistswapdex/safe-react#16]

**Comment by mainnet-pat** [comment]
same is in most recent issue: can not reproduce. had one signer in brave with metamask, another in safari over wallet connect to paytaca web (browser extension) app. swapping bch to mist in mistswap app worked just fine.

**Comment by kasumi-1** [comment]
i was trying with mobile paytaca

**Comment by mainnet-pat** [comment]
I am on ios and have no access to mobile paytaca. did you try to retest?

**Comment by mainnet-pat** [comment]
can we assume it is paytaca-specific issue?
