### ISSUE TITLE
show staked lp in mistswap farms as assets

### ISSUE THREAD

**Issue by kasumi-1** [mistswapdex/safe-react#19]
should be shown like in #18 but with detail that it is staked, and instead of send/receive should be link to mistswap farm page

**Comment by mainnet-pat** [comment]
do we want to steal debank's lunch? doing this would require some network calls from frontend. imagine there will be more factories from other dexes to check the LP token against. it scales quadratically in network usage

**Comment by mainnet-pat** [comment]
we can do this as mistswap exclusive feature by preparing a prefetched table of all lp tokens and their reserve token metadata info, the only call left would be a multicall with a batch of balanceOf to factory

**Comment by mainnet-pat** [comment]
done
